spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mentaltal-db.cli4trc7zh1k.ap-northeast-2.rds.amazonaws.com:13306/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: password
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#  jpa:
#     hibernate:
#       ddl-auto: create
#     show-sql: true
#     properties:
#       hibernate:
#         format_sql: true

#  sql:
#     init:
#       data-locations: classpath*:db/h2/data.sql

# logging:
#   level:
#     org:
#       springframework:
#         orm:
#           jpa: DEBUG

# server:
#   servlet:
#     encoding:
#       force-response: true

mail:
  address:
    admin: admin@gmail.com

jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 300

redis:
  host: localhost
  port: 6379
  password: redis
  timeout: 3000
  lettuce:
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0
