spring:
    username: admin
    url: jdbc:mysql://mentaltaldb.cezdgu2xim5u.ap-northeast-2.rds.amazonaws.com/dbmentaltal
    password: ${RDS_PASSWORD}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

mail:
  address:
    admin: sangw12477@gmail.com
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 40
  refresh-token-expiration-minutes: 420